### ISSUE TITLE
Improve GDAL installation comment in new_just 

### ISSUE THREAD

**Issue by deuscovrigus** [VisionSystemsInc/vsi_common#110]
the comment at 
https://github.com/VisionSystemsInc/vsi_common/blob/cecc646d0b0549667c11f2a85d9fd53ba1167703/linux/new_just#L914
needs some clarification. The gdal-bin version is not sufficient to match the python version. You need the libgdal-dev version to match also. The command gdal-config --version will give the answer. Is there perhaps an automatic way to set the gdal python package version (suggested) given the value of $(gdal-config --version) ?

**Comment by andyneff** [comment]
This is an example for debian stretch only, so that you can make those decisions and setup the gdal that's right for you

You can't always do `gdal-config --version` because not every version is available on pypi. Debain:stretch actually has a version slightly newer than 2.1.0, but this combo "works", as far as I've tested it.

There's always a possibility it won't work, and in that case you just have to build the python bindings from source manually.

Also, this example will be removed from this file in the future, and made as a stand alone example. So making it work on ubuntu/other OSes is not inline with the current direction.
