### ISSUE TITLE
Adding just subcommand target does not work as intended 

### ISSUE THREAD

**Issue by deuscovrigus** [VisionSystemsInc/vsi_common#83]
Adding new target entry to justfile does not work unless a comment is added on the same line that defines the target name

**Comment by andyneff** [comment]
A subcommand target without a comment isn't even in `parsed_help_a`, which is the list used to determine a subcommand. The fix is more complicated than at first glance.

- One idea is make everything get added to `parsed_help_a`, and filter out the comment-less ones for `print_help`. This will probably take a lot of sed editing
- Another idea is to make/use a different list for subcommand discovery in `justify`.

**Comment by andyneff** [comment]
Considering changing this to wontfix. If a subcommand doesn't have a comment, it's "hidden", so it shouldn't be in tab complete. Thoughts @scott-vsi?

**Comment by andyneff** [comment]
If you want to have tab complete help without writing a help, you can add a `#` after the case value, and it will show up in tab complete. This _is_ the intended use.

This means that the help will display a blank line for this command/subcommand. This is the expect behavior. If there is a great need to hide empty help targets, a flag could be added to do this. But currently there is not enough demand for this.
